var E_WHEEL_STATE;
(function (E_WHEEL_STATE) {
    E_WHEEL_STATE[E_WHEEL_STATE["IDLE"] = 0] = "IDLE";
    E_WHEEL_STATE[E_WHEEL_STATE["ROTATE"] = 1] = "ROTATE";
    E_WHEEL_STATE[E_WHEEL_STATE["STOP"] = 2] = "STOP";
    E_WHEEL_STATE[E_WHEEL_STATE["CALLBACK_DONE"] = 3] = "CALLBACK_DONE";
})(E_WHEEL_STATE || (E_WHEEL_STATE = {}));
;
var WheelNumber = 3;
var rules = [
    [0, 0, 0],
    [1, 1, 1],
    [2, 2, 2],
    [0, 1, 2],
    [2, 1, 0],
];
var E_WHEEL_VALUE;
(function (E_WHEEL_VALUE) {
    E_WHEEL_VALUE[E_WHEEL_VALUE["ORANGE"] = 0] = "ORANGE";
    E_WHEEL_VALUE[E_WHEEL_VALUE["BLUEBERRY"] = 1] = "BLUEBERRY";
    E_WHEEL_VALUE[E_WHEEL_VALUE["BAR"] = 2] = "BAR";
    E_WHEEL_VALUE[E_WHEEL_VALUE["BANANA"] = 3] = "BANANA";
    E_WHEEL_VALUE[E_WHEEL_VALUE["WATERMELON"] = 4] = "WATERMELON";
    E_WHEEL_VALUE[E_WHEEL_VALUE["GRAPE"] = 5] = "GRAPE";
    E_WHEEL_VALUE[E_WHEEL_VALUE["MANGO"] = 6] = "MANGO";
    E_WHEEL_VALUE[E_WHEEL_VALUE["SEVEN_NUMBER"] = 7] = "SEVEN_NUMBER";
    E_WHEEL_VALUE[E_WHEEL_VALUE["MAX"] = 8] = "MAX";
})(E_WHEEL_VALUE || (E_WHEEL_VALUE = {}));
;
var E_WHEEL_CALLBACK_STATE;
(function (E_WHEEL_CALLBACK_STATE) {
    E_WHEEL_CALLBACK_STATE[E_WHEEL_CALLBACK_STATE["NOT_DONE"] = 0] = "NOT_DONE";
    E_WHEEL_CALLBACK_STATE[E_WHEEL_CALLBACK_STATE["DONE"] = 1] = "DONE";
})(E_WHEEL_CALLBACK_STATE || (E_WHEEL_CALLBACK_STATE = {}));
//# sourceMappingURL=Definitions.js.map