enum E_WHEEL_STATE {
    IDLE,
    ROTATE,
    STOP,
    CALLBACK_DONE
};

const WheelNumber: number = 3;

enum E_WHEEL_VALUE {
    APPLE = 0,
    MANGOSTEEN,
    ORANGE,
    BLUEBERRY,
    BAR,
    BANANA,
    WATERMELON,
    GRAPE,
    MANGO,
    SEVEN_NUMBER,
    MAX
};

const WHEEL_VALUE_FREE_SPIN: E_WHEEL_VALUE = E_WHEEL_VALUE.SEVEN_NUMBER;
const WHEEL_VALUE_BONUS: E_WHEEL_VALUE = E_WHEEL_VALUE.BAR;