var E_WHEEL_STATE;
(function (E_WHEEL_STATE) {
    E_WHEEL_STATE[E_WHEEL_STATE["IDLE"] = 0] = "IDLE";
    E_WHEEL_STATE[E_WHEEL_STATE["ROTATE"] = 1] = "ROTATE";
    E_WHEEL_STATE[E_WHEEL_STATE["STOP"] = 2] = "STOP";
    E_WHEEL_STATE[E_WHEEL_STATE["CALLBACK_DONE"] = 3] = "CALLBACK_DONE";
})(E_WHEEL_STATE || (E_WHEEL_STATE = {}));
;
var WheelNumber = 3;
var E_WHEEL_VALUE;
(function (E_WHEEL_VALUE) {
    E_WHEEL_VALUE[E_WHEEL_VALUE["APPLE"] = 0] = "APPLE";
    E_WHEEL_VALUE[E_WHEEL_VALUE["MANGOSTEEN"] = 1] = "MANGOSTEEN";
    E_WHEEL_VALUE[E_WHEEL_VALUE["ORANGE"] = 2] = "ORANGE";
    E_WHEEL_VALUE[E_WHEEL_VALUE["BLUEBERRY"] = 3] = "BLUEBERRY";
    E_WHEEL_VALUE[E_WHEEL_VALUE["BAR"] = 4] = "BAR";
    E_WHEEL_VALUE[E_WHEEL_VALUE["BANANA"] = 5] = "BANANA";
    E_WHEEL_VALUE[E_WHEEL_VALUE["WATERMELON"] = 6] = "WATERMELON";
    E_WHEEL_VALUE[E_WHEEL_VALUE["GRAPE"] = 7] = "GRAPE";
    E_WHEEL_VALUE[E_WHEEL_VALUE["MANGO"] = 8] = "MANGO";
    E_WHEEL_VALUE[E_WHEEL_VALUE["SEVEN_NUMBER"] = 9] = "SEVEN_NUMBER";
    E_WHEEL_VALUE[E_WHEEL_VALUE["MAX"] = 10] = "MAX";
})(E_WHEEL_VALUE || (E_WHEEL_VALUE = {}));
;
var E_GAME_STATE;
(function (E_GAME_STATE) {
    E_GAME_STATE[E_GAME_STATE["INIT"] = 0] = "INIT";
    E_GAME_STATE[E_GAME_STATE["IDLE"] = 1] = "IDLE";
    E_GAME_STATE[E_GAME_STATE["SPIN"] = 2] = "SPIN";
    E_GAME_STATE[E_GAME_STATE["UPDATE_WHEEL"] = 3] = "UPDATE_WHEEL";
    E_GAME_STATE[E_GAME_STATE["PICK_BONUS"] = 4] = "PICK_BONUS";
    E_GAME_STATE[E_GAME_STATE["PAUSE"] = 5] = "PAUSE";
})(E_GAME_STATE || (E_GAME_STATE = {}));
var WHEEL_VALUE_FREE_SPIN = E_WHEEL_VALUE.SEVEN_NUMBER;
var WHEEL_VALUE_BONUS = E_WHEEL_VALUE.BAR;
//# sourceMappingURL=Definitions.js.map